version: '3.7'

services:
  flame-api:
    build: .
    image: postnikovda/flame-api:latest
    container_name: flame-api
    restart: always
    ports:
    - 8000:8000
    network_mode: "host"

  mongodb:
    image: mongo:4.2.3
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "mongodb:/data/db"

volumes:
  mongodb: